FROM ubuntu:20.04
FROM python:3.8.10

FROM osrf/ros:foxy-desktop

RUN apt-get update -y && \
    apt-get install -y python3-pip python-dev python3-opencv lsb-release curl gnupg2 python3-tk

# # Install ROS2 Foxy
# RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - && \
#     echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list

#RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

#RUN sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
# RUN apt-get update -y
# RUN apt-get install -y ros-foxy-desktop
# RUN echo "source /opt/ros/foxy/setup.bash" >> ~/.bashrc

# We copy just the requirements.txt first to leverage Docker cache
#COPY ./requirements.txt /app/requirements.txt

RUN mkdir -p /app/ros2_ws/src && . /opt/ros/foxy/setup.sh && cd /app/ros2_ws/src && ros2 pkg create doodlenet --build-type ament_python


# create a ROS2 python pkg
#RUN mkdir -p /app/ros2_ws/src && cd /app/ros2_ws/src && colcon build
#WORKDIR /app/ros2_ws/src
#RUN . /opt/ros/foxy/setup.sh && cd /app/ros2_ws/src && ros2 pkg create doodlenet --build-type ament_python && colcon build --packages-select doodlenet
#RUN ros2 pkg create doodlenet --build-type ament_python
#RUN colcon build --packages-select doodlenet

WORKDIR /app
COPY . /app/ros2_ws/src/doodlenet/doodlenet
RUN cd /app/ros2_ws/src && colcon build --packages-select doodlenet && cd /app/ros2_ws/src/doodlenet/doodlenet && cp setup.py ../. && pip install -r requirements.txt 

#RUN . /app/ros2_ws/src/install/setup.bash
#RUN ros2 run doodlenet inference

#RUN pip install -r requirements.txt

#colcon build --packages-select doodlenet

#RUN apt-get install -y ros-foxy-desktop
#RUN echo "source /opt/ros/foxy/setup.bash" >> ~/.bashrc

#RUN ros2 run demo_nodes_cpp talker

#ENTRYPOINT [ "python" ]
#CMD [ "demo_web_no_inference_only_lwir.py" ]

