FROM osrf/ros:foxy-desktop

RUN apt-get update -y && \
    apt-get install -y python3-pip python-dev python3-opencv lsb-release curl gnupg2 python3-tk

WORKDIR /app

COPY . /app

RUN pip install -r requirements_pc.txt

# download torch .pth model 
RUN mkdir model_weights && cd model_weights && gdown --id 1ooz2HL0Fjrk9hl8Z6-_k_6jQqH2_LOaa